import { useState } from "react";
import server from "./server";

function Transfer({ address, setBalance }) {
  const [sendAmount, setSendAmount] = useState("");
  const [recipient, setRecipient] = useState("");
  const [signature, setSignature] = useState("");
  const [publicKey, setPublicKey] = useState("");
  const [recoverBit, setRecoverBit] = useState(0);

  const setValue = (setter) => (evt) => setter(evt.target.value);

  async function transfer(evt) {
    evt.preventDefault();

    try {
      const {
        data: { balance },
      } = await server.post(`send`, {
        sender: address,
        amount: parseInt(sendAmount),
        recipient,
        signature,
        publicKey,
        recoverBit
      });
      setBalance(balance);
    } catch (ex) {
      alert(ex.response.data.message);
    }
  }

  //TODO add new input for signature and public key to generated by back-end script
  return (
    <form className="container transfer" onSubmit={transfer}>
      <h1>Send Transaction</h1>

      <label>
        Send Amount
        <input
          placeholder="1, 2, 3..."
          value={sendAmount}
          onChange={setValue(setSendAmount)}
        ></input>
      </label>

      <label>
        Recipient
        <input
          placeholder="Type an address, for example: 0x2"
          value={recipient}
          onChange={setValue(setRecipient)}
        ></input>
      </label>

      <label>
      Signature:
        <input
          placeholder="Type signature, for example: 3044***"
          value={signature}
          onChange={setValue(setSignature)}
        ></input>
      </label>

      <label>
        Public key: 
        <input
          placeholder="Type public key, for example: 0xe"
          value={publicKey}
          onChange={setValue(setPublicKey)}
        ></input>
      </label>

      <label>
        Recover Bit: 
        <input
          placeholder="Type recover bit, for example: 0"
          value={recoverBit}
          onChange={setValue(setRecoverBit)}
        ></input>
      </label>

      <input type="submit" className="button" value="Transfer" />
    </form>
  );
}

export default Transfer;
